version:  "3.1"
services:
  jobmanager:
    image: flink:1.18.1
    container_name: jobmanager
    hostname: jobmanager
    networks:
      - learn-flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.18.1
    container_name: taskmanager
    hostname: taskmanager
    networks:
      - learn-flink
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10  

networks:
  learn-flink:
    driver: bridge
