version: "3.1"
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - learn-flink
    ports:
      - "2181"
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=zookeeper
      - ZOO_CLIENT_PASSWORD=zookeeper_password
      - ZOO_MAX_SESSION_TIMEOUT=30000
    volumes:
      - ./data/zookeeper:/bitnami
  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    networks:
      - learn-flink
    ports:
      - "9002:9002"
      - "9093"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=zookeeper_password
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9002
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9002
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
    volumes:
      - ./data/kafka:/bitnami
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    hostname: kafkaui
    networks:
      - learn-flink
    ports:
      - "9082:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9002
  invest_generator:
    image: investgenerator:latest
    container_name: invest_generator
    hostname: investgenerator
    networks:
      - learn-flink
    ports:
      - "8080:8080"
  jobmanager:
    image: flink:1.18.1
    container_name: jobmanager
    hostname: jobmanager
    networks:
      - learn-flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.18.1
    container_name: taskmanager
    hostname: taskmanager
    networks:
      - learn-flink
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10  

networks:
  learn-flink:
    driver: bridge
